FROM golang:alpine3.18 AS build
RUN apk --no-cache add gcc g++ make git
WORKDIR /go/src/app
COPY . .
RUN go mod tidy
RUN go build -ldflags="-s -w" -o /api ./*.go

FROM alpine:3.18
RUN apk --no-cache add ca-certificates
WORKDIR /
COPY --from=build /api /api
COPY dev.env /
EXPOSE 1323
CMD ["/api"]